secret_key: "supersecret"
SECURITY_PASSWORD_SALT: "securesalt"
db_uri: 'postgresql+psycopg2://root:root@localhost:5432/billr'
NGROK_API_KEY: '2bX7eeWczqZcqrJU7GlibJ3nNm1_7mqgZfPfTAwfNfCcMtc1W'
ENDPOINT_SECRET: 'whsec_mkM1KnLZIh3KBU7UnQIUwzPA6FXkPWTl'