default:
  name: 'Dev'
  response: 'not-found 404'
  db:
    engine: 'postgresql'
  secret_key: settings.get('secret_key')
  SECURITY_PASSWORD_SALT: settings.get('SECURITY_PASSWORD_SALT')
  DB_NAME: 'scrape'
  DB_URI: 'postgresql+psycopg2://root:root@localhost:5432/billr'
  host: 'localhost'
  user: 'root'
  NGROK_API_KEY: '2bX7eeWczqZcqrJU7GlibJ3nNm1_7mqgZfPfTAwfNfCcMtc1W'
  ENDPOINT_SECRET: 'whsec_mkM1KnLZIh3KBU7UnQIUwzPA6FXkPWTl'
  STRIPE_API_KEY: 'sk_test_51Ociw0SCUb1HXhmanBwQYYgQddOB1AB7hOhKAyGdApZMnVKIVQMQPUhHYEjqr5UeZT6OMUslC2pI1NcbP3gftGCH00UYtYgoez'

